// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.15.8
// source: clientcompat.proto

package clientcompat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientCompatMessage_CompatServiceMethod int32

const (
	ClientCompatMessage_NOOP   ClientCompatMessage_CompatServiceMethod = 0
	ClientCompatMessage_METHOD ClientCompatMessage_CompatServiceMethod = 1
)

// Enum value maps for ClientCompatMessage_CompatServiceMethod.
var (
	ClientCompatMessage_CompatServiceMethod_name = map[int32]string{
		0: "NOOP",
		1: "METHOD",
	}
	ClientCompatMessage_CompatServiceMethod_value = map[string]int32{
		"NOOP":   0,
		"METHOD": 1,
	}
)

func (x ClientCompatMessage_CompatServiceMethod) Enum() *ClientCompatMessage_CompatServiceMethod {
	p := new(ClientCompatMessage_CompatServiceMethod)
	*p = x
	return p
}

func (x ClientCompatMessage_CompatServiceMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientCompatMessage_CompatServiceMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_clientcompat_proto_enumTypes[0].Descriptor()
}

func (ClientCompatMessage_CompatServiceMethod) Type() protoreflect.EnumType {
	return &file_clientcompat_proto_enumTypes[0]
}

func (x ClientCompatMessage_CompatServiceMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientCompatMessage_CompatServiceMethod.Descriptor instead.
func (ClientCompatMessage_CompatServiceMethod) EnumDescriptor() ([]byte, []int) {
	return file_clientcompat_proto_rawDescGZIP(), []int{3, 0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientcompat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_clientcompat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_clientcompat_proto_rawDescGZIP(), []int{0}
}

type Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V string `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
}

func (x *Req) Reset() {
	*x = Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientcompat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req) ProtoMessage() {}

func (x *Req) ProtoReflect() protoreflect.Message {
	mi := &file_clientcompat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req.ProtoReflect.Descriptor instead.
func (*Req) Descriptor() ([]byte, []int) {
	return file_clientcompat_proto_rawDescGZIP(), []int{1}
}

func (x *Req) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

type Resp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V int32 `protobuf:"varint,1,opt,name=v,proto3" json:"v,omitempty"`
}

func (x *Resp) Reset() {
	*x = Resp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientcompat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resp) ProtoMessage() {}

func (x *Resp) ProtoReflect() protoreflect.Message {
	mi := &file_clientcompat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resp.ProtoReflect.Descriptor instead.
func (*Resp) Descriptor() ([]byte, []int) {
	return file_clientcompat_proto_rawDescGZIP(), []int{2}
}

func (x *Resp) GetV() int32 {
	if x != nil {
		return x.V
	}
	return 0
}

type ClientCompatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceAddress string                                  `protobuf:"bytes,1,opt,name=service_address,json=serviceAddress,proto3" json:"service_address,omitempty"`
	Method         ClientCompatMessage_CompatServiceMethod `protobuf:"varint,2,opt,name=method,proto3,enum=twirp.clientcompat.ClientCompatMessage_CompatServiceMethod" json:"method,omitempty"`
	Request        []byte                                  `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *ClientCompatMessage) Reset() {
	*x = ClientCompatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientcompat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientCompatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCompatMessage) ProtoMessage() {}

func (x *ClientCompatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_clientcompat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCompatMessage.ProtoReflect.Descriptor instead.
func (*ClientCompatMessage) Descriptor() ([]byte, []int) {
	return file_clientcompat_proto_rawDescGZIP(), []int{3}
}

func (x *ClientCompatMessage) GetServiceAddress() string {
	if x != nil {
		return x.ServiceAddress
	}
	return ""
}

func (x *ClientCompatMessage) GetMethod() ClientCompatMessage_CompatServiceMethod {
	if x != nil {
		return x.Method
	}
	return ClientCompatMessage_NOOP
}

func (x *ClientCompatMessage) GetRequest() []byte {
	if x != nil {
		return x.Request
	}
	return nil
}

var File_clientcompat_proto protoreflect.FileDescriptor

var file_clientcompat_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x74, 0x77, 0x69, 0x72, 0x70, 0x2e, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x13, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x01, 0x76, 0x22, 0x14, 0x0a, 0x04, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0c,
	0x0a, 0x01, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x76, 0x22, 0xda, 0x01, 0x0a,
	0x13, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x53, 0x0a,
	0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3b, 0x2e,
	0x74, 0x77, 0x69, 0x72, 0x70, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x74, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2b, 0x0a, 0x13,
	0x43, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4f, 0x50, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x10, 0x01, 0x32, 0x90, 0x01, 0x0a, 0x0d, 0x43, 0x6f,
	0x6d, 0x70, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x17, 0x2e, 0x74, 0x77, 0x69, 0x72, 0x70, 0x2e, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x18,
	0x2e, 0x74, 0x77, 0x69, 0x72, 0x70, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x42, 0x0a, 0x0a, 0x4e, 0x6f, 0x6f, 0x70,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x19, 0x2e, 0x74, 0x77, 0x69, 0x72, 0x70, 0x2e, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x19, 0x2e, 0x74, 0x77, 0x69, 0x72, 0x70, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x11, 0x5a, 0x0f,
	0x2e, 0x2f, 0x3b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clientcompat_proto_rawDescOnce sync.Once
	file_clientcompat_proto_rawDescData = file_clientcompat_proto_rawDesc
)

func file_clientcompat_proto_rawDescGZIP() []byte {
	file_clientcompat_proto_rawDescOnce.Do(func() {
		file_clientcompat_proto_rawDescData = protoimpl.X.CompressGZIP(file_clientcompat_proto_rawDescData)
	})
	return file_clientcompat_proto_rawDescData
}

var file_clientcompat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_clientcompat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_clientcompat_proto_goTypes = []interface{}{
	(ClientCompatMessage_CompatServiceMethod)(0), // 0: twirp.clientcompat.ClientCompatMessage.CompatServiceMethod
	(*Empty)(nil),               // 1: twirp.clientcompat.Empty
	(*Req)(nil),                 // 2: twirp.clientcompat.Req
	(*Resp)(nil),                // 3: twirp.clientcompat.Resp
	(*ClientCompatMessage)(nil), // 4: twirp.clientcompat.ClientCompatMessage
}
var file_clientcompat_proto_depIdxs = []int32{
	0, // 0: twirp.clientcompat.ClientCompatMessage.method:type_name -> twirp.clientcompat.ClientCompatMessage.CompatServiceMethod
	2, // 1: twirp.clientcompat.CompatService.Method:input_type -> twirp.clientcompat.Req
	1, // 2: twirp.clientcompat.CompatService.NoopMethod:input_type -> twirp.clientcompat.Empty
	3, // 3: twirp.clientcompat.CompatService.Method:output_type -> twirp.clientcompat.Resp
	1, // 4: twirp.clientcompat.CompatService.NoopMethod:output_type -> twirp.clientcompat.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_clientcompat_proto_init() }
func file_clientcompat_proto_init() {
	if File_clientcompat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_clientcompat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientcompat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientcompat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientcompat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientCompatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clientcompat_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clientcompat_proto_goTypes,
		DependencyIndexes: file_clientcompat_proto_depIdxs,
		EnumInfos:         file_clientcompat_proto_enumTypes,
		MessageInfos:      file_clientcompat_proto_msgTypes,
	}.Build()
	File_clientcompat_proto = out.File
	file_clientcompat_proto_rawDesc = nil
	file_clientcompat_proto_goTypes = nil
	file_clientcompat_proto_depIdxs = nil
}
