# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snake_case_names.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='snake_case_names.proto',
  package='twirp.internal.twirptest.snake_case_names',
  syntax='proto3',
  serialized_options=b'Z\022./snake_case_names',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16snake_case_names.proto\x12)twirp.internal.twirptest.snake_case_names\"`\n\x0eMakeHatArgs_v1\x1a\x33\n\x06Hat_v1\x12\x0c\n\x04size\x18\x01 \x01(\x05\x12\r\n\x05\x63olor\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x1a\x19\n\x07Size_v1\x12\x0e\n\x06inches\x18\x01 \x01(\x05\x32\xa4\x01\n\x0eHaberdasher_v1\x12\x91\x01\n\nMakeHat_v1\x12\x41.twirp.internal.twirptest.snake_case_names.MakeHatArgs_v1.Size_v1\x1a@.twirp.internal.twirptest.snake_case_names.MakeHatArgs_v1.Hat_v1B\x14Z\x12./snake_case_namesb\x06proto3'
)




_MAKEHATARGS_V1_HAT_V1 = _descriptor.Descriptor(
  name='Hat_v1',
  full_name='twirp.internal.twirptest.snake_case_names.MakeHatArgs_v1.Hat_v1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='twirp.internal.twirptest.snake_case_names.MakeHatArgs_v1.Hat_v1.size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='twirp.internal.twirptest.snake_case_names.MakeHatArgs_v1.Hat_v1.color', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='twirp.internal.twirptest.snake_case_names.MakeHatArgs_v1.Hat_v1.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=138,
)

_MAKEHATARGS_V1_SIZE_V1 = _descriptor.Descriptor(
  name='Size_v1',
  full_name='twirp.internal.twirptest.snake_case_names.MakeHatArgs_v1.Size_v1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='inches', full_name='twirp.internal.twirptest.snake_case_names.MakeHatArgs_v1.Size_v1.inches', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=165,
)

_MAKEHATARGS_V1 = _descriptor.Descriptor(
  name='MakeHatArgs_v1',
  full_name='twirp.internal.twirptest.snake_case_names.MakeHatArgs_v1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_MAKEHATARGS_V1_HAT_V1, _MAKEHATARGS_V1_SIZE_V1, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=165,
)

_MAKEHATARGS_V1_HAT_V1.containing_type = _MAKEHATARGS_V1
_MAKEHATARGS_V1_SIZE_V1.containing_type = _MAKEHATARGS_V1
DESCRIPTOR.message_types_by_name['MakeHatArgs_v1'] = _MAKEHATARGS_V1
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MakeHatArgs_v1 = _reflection.GeneratedProtocolMessageType('MakeHatArgs_v1', (_message.Message,), {

  'Hat_v1' : _reflection.GeneratedProtocolMessageType('Hat_v1', (_message.Message,), {
    'DESCRIPTOR' : _MAKEHATARGS_V1_HAT_V1,
    '__module__' : 'snake_case_names_pb2'
    # @@protoc_insertion_point(class_scope:twirp.internal.twirptest.snake_case_names.MakeHatArgs_v1.Hat_v1)
    })
  ,

  'Size_v1' : _reflection.GeneratedProtocolMessageType('Size_v1', (_message.Message,), {
    'DESCRIPTOR' : _MAKEHATARGS_V1_SIZE_V1,
    '__module__' : 'snake_case_names_pb2'
    # @@protoc_insertion_point(class_scope:twirp.internal.twirptest.snake_case_names.MakeHatArgs_v1.Size_v1)
    })
  ,
  'DESCRIPTOR' : _MAKEHATARGS_V1,
  '__module__' : 'snake_case_names_pb2'
  # @@protoc_insertion_point(class_scope:twirp.internal.twirptest.snake_case_names.MakeHatArgs_v1)
  })
_sym_db.RegisterMessage(MakeHatArgs_v1)
_sym_db.RegisterMessage(MakeHatArgs_v1.Hat_v1)
_sym_db.RegisterMessage(MakeHatArgs_v1.Size_v1)


DESCRIPTOR._options = None

_HABERDASHER_V1 = _descriptor.ServiceDescriptor(
  name='Haberdasher_v1',
  full_name='twirp.internal.twirptest.snake_case_names.Haberdasher_v1',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=168,
  serialized_end=332,
  methods=[
  _descriptor.MethodDescriptor(
    name='MakeHat_v1',
    full_name='twirp.internal.twirptest.snake_case_names.Haberdasher_v1.MakeHat_v1',
    index=0,
    containing_service=None,
    input_type=_MAKEHATARGS_V1_SIZE_V1,
    output_type=_MAKEHATARGS_V1_HAT_V1,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HABERDASHER_V1)

DESCRIPTOR.services_by_name['Haberdasher_v1'] = _HABERDASHER_V1

# @@protoc_insertion_point(module_scope)
