# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: multiple1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='multiple1.proto',
  package='twirp.internal.twirptest.multiple',
  syntax='proto3',
  serialized_options=b'Z\010multiple',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fmultiple1.proto\x12!twirp.internal.twirptest.multiple\"\x06\n\x04Msg12`\n\x04Svc1\x12X\n\x04Send\x12\'.twirp.internal.twirptest.multiple.Msg1\x1a\'.twirp.internal.twirptest.multiple.Msg1B\nZ\x08multipleb\x06proto3'
)




_MSG1 = _descriptor.Descriptor(
  name='Msg1',
  full_name='twirp.internal.twirptest.multiple.Msg1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=60,
)

DESCRIPTOR.message_types_by_name['Msg1'] = _MSG1
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Msg1 = _reflection.GeneratedProtocolMessageType('Msg1', (_message.Message,), {
  'DESCRIPTOR' : _MSG1,
  '__module__' : 'multiple1_pb2'
  # @@protoc_insertion_point(class_scope:twirp.internal.twirptest.multiple.Msg1)
  })
_sym_db.RegisterMessage(Msg1)


DESCRIPTOR._options = None

_SVC1 = _descriptor.ServiceDescriptor(
  name='Svc1',
  full_name='twirp.internal.twirptest.multiple.Svc1',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=62,
  serialized_end=158,
  methods=[
  _descriptor.MethodDescriptor(
    name='Send',
    full_name='twirp.internal.twirptest.multiple.Svc1.Send',
    index=0,
    containing_service=None,
    input_type=_MSG1,
    output_type=_MSG1,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SVC1)

DESCRIPTOR.services_by_name['Svc1'] = _SVC1

# @@protoc_insertion_point(module_scope)
