# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: importer_local.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import importer_local_msgdef_pb2 as importer__local__msgdef__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='importer_local.proto',
  package='twirp.internal.twirptest.importer_local',
  syntax='proto3',
  serialized_options=b'Z;github.com/twitchtv/twirp/internal/twirptest/importer_local',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14importer_local.proto\x12\'twirp.internal.twirptest.importer_local\x1a\x1bimporter_local_msgdef.proto2i\n\x03Svc\x12\x62\n\x04Send\x12,.twirp.internal.twirptest.importer_local.Msg\x1a,.twirp.internal.twirptest.importer_local.MsgB=Z;github.com/twitchtv/twirp/internal/twirptest/importer_localb\x06proto3'
  ,
  dependencies=[importer__local__msgdef__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_SVC = _descriptor.ServiceDescriptor(
  name='Svc',
  full_name='twirp.internal.twirptest.importer_local.Svc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=94,
  serialized_end=199,
  methods=[
  _descriptor.MethodDescriptor(
    name='Send',
    full_name='twirp.internal.twirptest.importer_local.Svc.Send',
    index=0,
    containing_service=None,
    input_type=importer__local__msgdef__pb2._MSG,
    output_type=importer__local__msgdef__pb2._MSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SVC)

DESCRIPTOR.services_by_name['Svc'] = _SVC

# @@protoc_insertion_point(module_scope)
