// Code generated by protoc-gen-go. DO NOT EDIT.
// source: importer_local_msgdef.proto

package importer_local

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Msg struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f42ae8c7fcacc34, []int{0}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Msg)(nil), "twirp.internal.twirptest.importer_local.Msg")
}

func init() { proto.RegisterFile("importer_local_msgdef.proto", fileDescriptor_2f42ae8c7fcacc34) }

var fileDescriptor_2f42ae8c7fcacc34 = []byte{
	// 127 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xce, 0xcc, 0x2d, 0xc8,
	0x2f, 0x2a, 0x49, 0x2d, 0x8a, 0xcf, 0xc9, 0x4f, 0x4e, 0xcc, 0x89, 0xcf, 0x2d, 0x4e, 0x4f, 0x49,
	0x4d, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x52, 0x2f, 0x29, 0xcf, 0x2c, 0x2a, 0xd0, 0xcb,
	0xcc, 0x2b, 0x49, 0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x03, 0x73, 0x4b, 0x52, 0x8b, 0x4b, 0xf4, 0x50,
	0x75, 0x29, 0xb1, 0x72, 0x31, 0xfb, 0x16, 0xa7, 0x3b, 0xd9, 0x46, 0x59, 0xa7, 0x67, 0x96, 0x64,
	0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x97, 0x94, 0x67, 0x96, 0x24, 0x67, 0x94, 0x94, 0xe9,
	0x83, 0xb5, 0xe9, 0xc3, 0x4c, 0xd1, 0x87, 0x9b, 0xa2, 0x8f, 0x6a, 0x4a, 0x12, 0x1b, 0xd8, 0x56,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x41, 0x34, 0x41, 0x94, 0x00, 0x00, 0x00,
}
