# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: y/y.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='y/y.proto',
  package='twirp.internal.twirptest.importmapping.y',
  syntax='proto3',
  serialized_options=b'Z\004./;y',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ty/y.proto\x12(twirp.internal.twirptest.importmapping.y\"\x06\n\x04MsgYB\x06Z\x04./;yb\x06proto3'
)




_MSGY = _descriptor.Descriptor(
  name='MsgY',
  full_name='twirp.internal.twirptest.importmapping.y.MsgY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=61,
)

DESCRIPTOR.message_types_by_name['MsgY'] = _MSGY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgY = _reflection.GeneratedProtocolMessageType('MsgY', (_message.Message,), {
  'DESCRIPTOR' : _MSGY,
  '__module__' : 'y.y_pb2'
  # @@protoc_insertion_point(class_scope:twirp.internal.twirptest.importmapping.y.MsgY)
  })
_sym_db.RegisterMessage(MsgY)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
