# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: y/y.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='y/y.proto',
  package='twirp.twirptest.importmapping.y',
  syntax='proto3',
  serialized_pb=_b('\n\ty/y.proto\x12\x1ftwirp.twirptest.importmapping.y\"\x06\n\x04MsgYb\x06proto3')
)




_MSGY = _descriptor.Descriptor(
  name='MsgY',
  full_name='twirp.twirptest.importmapping.y.MsgY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=52,
)

DESCRIPTOR.message_types_by_name['MsgY'] = _MSGY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgY = _reflection.GeneratedProtocolMessageType('MsgY', (_message.Message,), dict(
  DESCRIPTOR = _MSGY,
  __module__ = 'y.y_pb2'
  # @@protoc_insertion_point(class_scope:twirp.twirptest.importmapping.y.MsgY)
  ))
_sym_db.RegisterMessage(MsgY)


# @@protoc_insertion_point(module_scope)
